//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    
    public partial class GenderCountResult
    {
        public Nullable<int> Male { get; set; }
        public Nullable<int> Female { get; set; }
    }
}
