//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTable
    {
        public int PaymentId { get; set; }
        public int EmployeeId { get; set; }
        public string Month { get; set; }
        public int Amount { get; set; }
        public System.DateTime PaidOn { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
