//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    
    public partial class PaymentHistoryMYResult
    {
        public int Amount { get; set; }
        public string Month { get; set; }
        public System.DateTime PaidOn { get; set; }
        public int PaymentId { get; set; }
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string FatherName { get; set; }
        public string Qualifications { get; set; }
        public string Adress { get; set; }
        public string PrimaryContact { get; set; }
        public string SecondaryContact { get; set; }
        public int Age { get; set; }
        public System.DateTime JoinedOn { get; set; }
        public string Subject { get; set; }
        public string Gender { get; set; }
    }
}
