//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    
    public partial class SearchStudentInfoByGradeResult
    {
        public int AdmissionNumber { get; set; }
        public string AcademicYear { get; set; }
        public string Active { get; set; }
        public System.DateTime DateOfAdmission { get; set; }
        public System.DateTime DOB { get; set; }
        public string Emergency { get; set; }
        public string FatherName { get; set; }
        public string FatherCNIC { get; set; }
        public string FarherOccupation { get; set; }
        public string FatherDesignation { get; set; }
        public string FatherWorkAddress { get; set; }
        public string FirstLanguage { get; set; }
        public string Gender { get; set; }
        public string Grade { get; set; }
        public string GuardianName { get; set; }
        public string GuardianRelation { get; set; }
        public string GuardianAddress { get; set; }
        public string HomeAddress { get; set; }
        public string Mobile { get; set; }
        public string MotherName { get; set; }
        public string MotherCNIC { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherDesignation { get; set; }
        public string MotherWorkAddress { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string ReasonOfLeaving { get; set; }
        public string Phone { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PreviousSchoolName { get; set; }
        public string Studied { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte[] TimeOfAdmission { get; set; }
        public Nullable<System.DateTime> DateOfWithdraw { get; set; }
        public byte[] StudentImage { get; set; }
        public byte[] StudentFormBay { get; set; }
        public byte[] StudentBC { get; set; }
        public string ClassAdmitedIn { get; set; }
    }
}
