//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldStockTable
    {
        public int SellId { get; set; }
        public string BuyerName { get; set; }
        public int SellQuantity { get; set; }
        public int Price { get; set; }
        public int StockId { get; set; }
        public System.DateTime SoldOn { get; set; }
    
        public virtual StockTable StockTable { get; set; }
    }
}
