//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockTable()
        {
            this.SoldStockTables = new HashSet<SoldStockTable>();
        }
    
        public int StockId { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldStockTable> SoldStockTables { get; set; }
    }
}
