//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDiscountTable
    {
        public int StudentDiscountID { get; set; }
        public int DiscountID { get; set; }
        public int AdmissionNumber { get; set; }
        public int FeeID { get; set; }
        public Nullable<int> DiscountedFee { get; set; }
    
        public virtual DiscountTable DiscountTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
